### ISSUE TITLE
Move junit dependency to test dependencies

### ISSUE THREAD

**Issue by mcandre** [xedin/disruptor_thrift_server#12]
Please move the JUnit dependency to a test-scoped dependency section, to reduce the memory footprint of downstream software.

Tutorial:

http://books.sonatype.com/mvnex-book/reference/customizing-sect-test-scope.html

**Comment by xedin** [comment]
This has been done by PR https://github.com/xedin/disruptor_thrift_server/pull/10 and already merged in.
