### ISSUE TITLE
Fix selectors to skip interest changes in-between processing of the command.

### ISSUE THREAD

**Issue by xedin** [xedin/disruptor_thrift_server#6]
Here is the text from CASSANDRA-6815:

it will be good to ensure that there is no key interests for read/writes between read/write (i.e. when we're waiting for message to be processed in threadpool). Without that patch there can be 100% cpu usage sometimes in case some data will be still available in tcp channel for reading.

**Comment by rbranson** [comment]
Pretty sure we're hitting this in production right now. Any fixes / workarounds?

**Comment by rbranson** [comment]
There's this patch. https://issues.apache.org/jira/secure/attachment/12633656/disruptor-high-cpu.patch

**Comment by xedin** [comment]
Thanks for the patch, @rbranson. I have back logged it because nobody complained, will release new version today with this patch included.

**Comment by rbranson** [comment]
I didn't write the patch btw, just found it in https://issues.apache.org/jira/browse/CASSANDRA-6285. Appears to be working on a machine that I applied it to.

**Comment by xedin** [comment]
Yeah, I saw that. Let me re-phrase, thanks for confirming that it's works :)

**Comment by xedin** [comment]
Ok, released 0.3.8 should be available in the central shortly.

**Comment by rbranson** [comment]
I'm not super sure it works. Instead of CPU spikes, I'm seeing CPU drop-outs and connections dropping. Not sure of the cause yet.

**Comment by xedin** [comment]
Ok, please keep me posted.
